### ISSUE TITLE
Improvement: Add support for API v3

### ISSUE THREAD

**Issue by ZonCen** [martindahlswe/SwiftJiraKit#5]
Today this is using the API v2, which can have some functions needed by some but that can also be true for V3. 

Therefore I suggest that you add the possibility to use V3 and V2 in the codebase.

**Comment by martindahlswe** [comment]
I will reject this improvement suggestion just base off of my available time to account for both v2 and v3.
My current use-case is based off of v2, when that has been completed I'll look into implementing v3,
